// File: xula.v
// Generated by MyHDL 0.9.0
// Date: Sat Oct 31 21:02:29 2015


`timescale 1ns/10ps

module xula (
    clock,
    button,
    led
);


input clock;
input button;
output led;
reg led;






always @(posedge clock) begin: XULA_RTL
    led <= button;
end

endmodule
