-- File: xula.vhd
-- Generated by MyHDL 0.9.0
-- Date: Sat Oct 31 21:02:29 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity xula is
    port (
        clock: in std_logic;
        button: in std_logic;
        led: out std_logic
    );
end entity xula;


architecture MyHDL of xula is






begin





XULA_RTL: process (clock) is
begin
    if rising_edge(clock) then
        led <= button;
    end if;
end process XULA_RTL;

end architecture MyHDL;
