// File: siir_sos_hdl.v
// Generated by MyHDL 0.9.0
// Date: Mon Oct 26 14:14:03 2015


`timescale 1ns/10ps

module siir_sos_hdl (
    clk,
    x,
    y,
    ts
);


input clk;
input signed [23:0] x;
output signed [23:0] y;
reg signed [23:0] y;
input ts;

wire signed [48:0] ListOfIir_4_yacc;
reg signed [23:0] ListOfIir_4_x;
wire signed [48:0] ListOfIir_3_yacc;
reg signed [23:0] ListOfIir_3_x;
wire signed [48:0] ListOfIir_2_yacc;
reg signed [23:0] ListOfIir_2_x;
wire signed [48:0] ListOfIir_1_yacc;
reg signed [23:0] ListOfIir_1_x;
wire signed [48:0] ListOfIir_0_yacc;

reg signed [48:0] ListOfIir_4_ffd [0:2-1];
reg signed [48:0] ListOfIir_4_fbd [0:2-1];
reg signed [48:0] ListOfIir_3_ffd [0:2-1];
reg signed [48:0] ListOfIir_3_fbd [0:2-1];
reg signed [48:0] ListOfIir_2_ffd [0:2-1];
reg signed [48:0] ListOfIir_2_fbd [0:2-1];
reg signed [48:0] ListOfIir_1_ffd [0:2-1];
reg signed [48:0] ListOfIir_1_fbd [0:2-1];
reg signed [48:0] ListOfIir_0_ffd [0:2-1];
reg signed [48:0] ListOfIir_0_fbd [0:2-1];




always @(posedge clk) begin: SIIR_SOS_HDL_LISTOFIIR_0_RTL_IIR
    if (ts) begin
        ListOfIir_0_ffd[1] <= ListOfIir_0_ffd[0];
        ListOfIir_0_ffd[0] <= x;
        ListOfIir_0_fbd[1] <= ListOfIir_0_fbd[0];
        ListOfIir_0_fbd[0] <= $signed(ListOfIir_0_yacc[48-1:23]);
    end
    ListOfIir_1_x <= $signed(ListOfIir_0_yacc[48-1:23]);
end



assign ListOfIir_0_yacc = (((((8388608 * x) + (16800336 * ListOfIir_0_ffd[0])) + (8385201 * ListOfIir_0_ffd[1])) - ((-14723363) * ListOfIir_0_fbd[0])) - (6463234 * ListOfIir_0_fbd[1]));


always @(posedge clk) begin: SIIR_SOS_HDL_LISTOFIIR_1_RTL_IIR
    if (ts) begin
        ListOfIir_1_ffd[1] <= ListOfIir_1_ffd[0];
        ListOfIir_1_ffd[0] <= ListOfIir_1_x;
        ListOfIir_1_fbd[1] <= ListOfIir_1_fbd[0];
        ListOfIir_1_fbd[0] <= $signed(ListOfIir_1_yacc[48-1:23]);
    end
    ListOfIir_2_x <= $signed(ListOfIir_1_yacc[48-1:23]);
end



assign ListOfIir_1_yacc = (((((8388608 * ListOfIir_1_x) + (17547599 * ListOfIir_1_ffd[0])) + (9186593 * ListOfIir_1_ffd[1])) - ((-14890123) * ListOfIir_1_fbd[0])) - (6631526 * ListOfIir_1_fbd[1]));


always @(posedge clk) begin: SIIR_SOS_HDL_LISTOFIIR_2_RTL_IIR
    if (ts) begin
        ListOfIir_2_ffd[1] <= ListOfIir_2_ffd[0];
        ListOfIir_2_ffd[0] <= ListOfIir_2_x;
        ListOfIir_2_fbd[1] <= ListOfIir_2_fbd[0];
        ListOfIir_2_fbd[0] <= $signed(ListOfIir_2_yacc[48-1:23]);
    end
    ListOfIir_3_x <= $signed(ListOfIir_2_yacc[48-1:23]);
end



assign ListOfIir_2_yacc = (((((8388608 * ListOfIir_2_x) + (17049881 * ListOfIir_2_ffd[0])) + (8688210 * ListOfIir_2_ffd[1])) - ((-15219500) * ListOfIir_2_fbd[0])) - (6963733 * ListOfIir_2_fbd[1]));


always @(posedge clk) begin: SIIR_SOS_HDL_LISTOFIIR_3_RTL_IIR
    if (ts) begin
        ListOfIir_3_ffd[1] <= ListOfIir_3_ffd[0];
        ListOfIir_3_ffd[0] <= ListOfIir_3_x;
        ListOfIir_3_fbd[1] <= ListOfIir_3_fbd[0];
        ListOfIir_3_fbd[0] <= $signed(ListOfIir_3_yacc[48-1:23]);
    end
    ListOfIir_4_x <= $signed(ListOfIir_3_yacc[48-1:23]);
end



assign ListOfIir_3_yacc = (((((8388608 * ListOfIir_3_x) + (16467145 * ListOfIir_3_ffd[0])) + (8104671 * ListOfIir_3_ffd[1])) - ((-15696621) * ListOfIir_3_fbd[0])) - (7445015 * ListOfIir_3_fbd[1]));


always @(posedge clk) begin: SIIR_SOS_HDL_LISTOFIIR_4_RTL_IIR
    if (ts) begin
        ListOfIir_4_ffd[1] <= ListOfIir_4_ffd[0];
        ListOfIir_4_ffd[0] <= ListOfIir_4_x;
        ListOfIir_4_fbd[1] <= ListOfIir_4_fbd[0];
        ListOfIir_4_fbd[0] <= $signed(ListOfIir_4_yacc[48-1:23]);
    end
    y <= $signed(ListOfIir_4_yacc[48-1:23]);
end



assign ListOfIir_4_yacc = (((((8388608 * ListOfIir_4_x) + (16021119 * ListOfIir_4_ffd[0])) + (7658009 * ListOfIir_4_ffd[1])) - ((-16297371) * ListOfIir_4_fbd[0])) - (8051015 * ListOfIir_4_fbd[1]));

endmodule
