-- File: siir_sos_hdl.vhd
-- Generated by MyHDL 0.9.0
-- Date: Mon Oct 26 14:14:03 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity siir_sos_hdl is
    port (
        clk: in std_logic;
        x: in signed (23 downto 0);
        y: out signed (23 downto 0);
        ts: in std_logic
    );
end entity siir_sos_hdl;


architecture MyHDL of siir_sos_hdl is


constant a1: integer := -14723363;
constant Q: integer := 23;
constant a2: integer := 6463234;
constant b0: integer := 2**23;
constant Qd: integer := 48;
constant b2: integer := 8385201;
constant b1: integer := 16800336;



signal ListOfIir_4_yacc: signed (48 downto 0);
signal ListOfIir_4_x: signed (23 downto 0);
signal ListOfIir_3_yacc: signed (48 downto 0);
signal ListOfIir_3_x: signed (23 downto 0);
signal ListOfIir_2_yacc: signed (48 downto 0);
signal ListOfIir_2_x: signed (23 downto 0);
signal ListOfIir_1_yacc: signed (48 downto 0);
signal ListOfIir_1_x: signed (23 downto 0);
signal ListOfIir_0_yacc: signed (48 downto 0);
type t_array_ListOfIir_4_ffd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_4_ffd: t_array_ListOfIir_4_ffd;
type t_array_ListOfIir_4_fbd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_4_fbd: t_array_ListOfIir_4_fbd;
type t_array_ListOfIir_3_ffd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_3_ffd: t_array_ListOfIir_3_ffd;
type t_array_ListOfIir_3_fbd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_3_fbd: t_array_ListOfIir_3_fbd;
type t_array_ListOfIir_2_ffd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_2_ffd: t_array_ListOfIir_2_ffd;
type t_array_ListOfIir_2_fbd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_2_fbd: t_array_ListOfIir_2_fbd;
type t_array_ListOfIir_1_ffd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_1_ffd: t_array_ListOfIir_1_ffd;
type t_array_ListOfIir_1_fbd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_1_fbd: t_array_ListOfIir_1_fbd;
type t_array_ListOfIir_0_ffd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_0_ffd: t_array_ListOfIir_0_ffd;
type t_array_ListOfIir_0_fbd is array(0 to 2-1) of signed (48 downto 0);
signal ListOfIir_0_fbd: t_array_ListOfIir_0_fbd;

begin





SIIR_SOS_HDL_LISTOFIIR_0_RTL_IIR: process (clk) is
begin
    if rising_edge(clk) then
        if bool(ts) then
            ListOfIir_0_ffd(1) <= ListOfIir_0_ffd(0);
            ListOfIir_0_ffd(0) <= resize(x, 49);
            ListOfIir_0_fbd(1) <= ListOfIir_0_fbd(0);
            ListOfIir_0_fbd(0) <= resize(signed(unsigned(ListOfIir_0_yacc(Qd-1 downto Q))), 49);
        end if;
        ListOfIir_1_x <= resize(signed(unsigned(ListOfIir_0_yacc(Qd-1 downto Q))), 24);
    end if;
end process SIIR_SOS_HDL_LISTOFIIR_0_RTL_IIR;



ListOfIir_0_yacc <= resize(((((b0 * x) + (b1 * ListOfIir_0_ffd(0))) + (b2 * ListOfIir_0_ffd(1))) - (a1 * ListOfIir_0_fbd(0))) - (a2 * ListOfIir_0_fbd(1)), 49);


SIIR_SOS_HDL_LISTOFIIR_1_RTL_IIR: process (clk) is
begin
    if rising_edge(clk) then
        if bool(ts) then
            ListOfIir_1_ffd(1) <= ListOfIir_1_ffd(0);
            ListOfIir_1_ffd(0) <= resize(ListOfIir_1_x, 49);
            ListOfIir_1_fbd(1) <= ListOfIir_1_fbd(0);
            ListOfIir_1_fbd(0) <= resize(signed(unsigned(ListOfIir_1_yacc(Qd-1 downto Q))), 49);
        end if;
        ListOfIir_2_x <= resize(signed(unsigned(ListOfIir_1_yacc(Qd-1 downto Q))), 24);
    end if;
end process SIIR_SOS_HDL_LISTOFIIR_1_RTL_IIR;



ListOfIir_1_yacc <= resize(((((b0 * ListOfIir_1_x) + (17547599 * ListOfIir_1_ffd(0))) + (9186593 * ListOfIir_1_ffd(1))) - ((- 14890123) * ListOfIir_1_fbd(0))) - (6631526 * ListOfIir_1_fbd(1)), 49);


SIIR_SOS_HDL_LISTOFIIR_2_RTL_IIR: process (clk) is
begin
    if rising_edge(clk) then
        if bool(ts) then
            ListOfIir_2_ffd(1) <= ListOfIir_2_ffd(0);
            ListOfIir_2_ffd(0) <= resize(ListOfIir_2_x, 49);
            ListOfIir_2_fbd(1) <= ListOfIir_2_fbd(0);
            ListOfIir_2_fbd(0) <= resize(signed(unsigned(ListOfIir_2_yacc(Qd-1 downto Q))), 49);
        end if;
        ListOfIir_3_x <= resize(signed(unsigned(ListOfIir_2_yacc(Qd-1 downto Q))), 24);
    end if;
end process SIIR_SOS_HDL_LISTOFIIR_2_RTL_IIR;



ListOfIir_2_yacc <= resize(((((b0 * ListOfIir_2_x) + (17049881 * ListOfIir_2_ffd(0))) + (8688210 * ListOfIir_2_ffd(1))) - ((- 15219500) * ListOfIir_2_fbd(0))) - (6963733 * ListOfIir_2_fbd(1)), 49);


SIIR_SOS_HDL_LISTOFIIR_3_RTL_IIR: process (clk) is
begin
    if rising_edge(clk) then
        if bool(ts) then
            ListOfIir_3_ffd(1) <= ListOfIir_3_ffd(0);
            ListOfIir_3_ffd(0) <= resize(ListOfIir_3_x, 49);
            ListOfIir_3_fbd(1) <= ListOfIir_3_fbd(0);
            ListOfIir_3_fbd(0) <= resize(signed(unsigned(ListOfIir_3_yacc(Qd-1 downto Q))), 49);
        end if;
        ListOfIir_4_x <= resize(signed(unsigned(ListOfIir_3_yacc(Qd-1 downto Q))), 24);
    end if;
end process SIIR_SOS_HDL_LISTOFIIR_3_RTL_IIR;



ListOfIir_3_yacc <= resize(((((b0 * ListOfIir_3_x) + (16467145 * ListOfIir_3_ffd(0))) + (8104671 * ListOfIir_3_ffd(1))) - ((- 15696621) * ListOfIir_3_fbd(0))) - (7445015 * ListOfIir_3_fbd(1)), 49);


SIIR_SOS_HDL_LISTOFIIR_4_RTL_IIR: process (clk) is
begin
    if rising_edge(clk) then
        if bool(ts) then
            ListOfIir_4_ffd(1) <= ListOfIir_4_ffd(0);
            ListOfIir_4_ffd(0) <= resize(ListOfIir_4_x, 49);
            ListOfIir_4_fbd(1) <= ListOfIir_4_fbd(0);
            ListOfIir_4_fbd(0) <= resize(signed(unsigned(ListOfIir_4_yacc(Qd-1 downto Q))), 49);
        end if;
        y <= resize(signed(unsigned(ListOfIir_4_yacc(Qd-1 downto Q))), 24);
    end if;
end process SIIR_SOS_HDL_LISTOFIIR_4_RTL_IIR;



ListOfIir_4_yacc <= resize(((((b0 * ListOfIir_4_x) + (16021119 * ListOfIir_4_ffd(0))) + (7658009 * ListOfIir_4_ffd(1))) - ((- 16297371) * ListOfIir_4_fbd(0))) - (8051015 * ListOfIir_4_fbd(1)), 49);

end architecture MyHDL;
