-- File: m_clk_io_gen.vhd
-- Generated by MyHDL 0.8dev
-- Date: Tue Apr 30 20:11:49 2013


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_08.all;

entity m_clk_io_gen is
    port (
        clock: in std_logic;
        reset: in std_logic;
        clk_io: inout std_logic;
        clk_io_posedge: out std_logic
    );
end entity m_clk_io_gen;
-- generate an slow (very slow) clock for serail comms 

architecture MyHDL of m_clk_io_gen is

signal cnt: unsigned(8 downto 0);

begin




M_CLK_IO_GEN_HDL: process (clock, reset) is
begin
    if (reset = '0') then
        clk_io <= '0';
        cnt <= 000000001;
        clk_io_posedge <= '0';
    elsif rising_edge(clock) then
        if (cnt = 500) then
            cnt <= "000000001";
            clk_io <= stdl((not bool(clk_io)));
            if (not bool(clk_io)) then
                clk_io_posedge <= '1';
            end if;
        else
            cnt <= (cnt + 1);
            clk_io_posedge <= '0';
        end if;
    end if;
end process M_CLK_IO_GEN_HDL;

end architecture MyHDL;
