// File: m_clk_io_gen.v
// Generated by MyHDL 0.8dev
// Date: Tue Apr 30 20:11:49 2013


`timescale 1ns/10ps

module m_clk_io_gen (
    clock,
    reset,
    clk_io,
    clk_io_posedge
);
// generate an slow (very slow) clock for serail comms 

input clock;
input reset;
output clk_io;
reg clk_io;
output clk_io_posedge;
reg clk_io_posedge;

reg [8:0] cnt;





always @(posedge clock, negedge reset) begin: M_CLK_IO_GEN_HDL
    if (reset == 0) begin
        clk_io <= 0;
        cnt <= 1;
        clk_io_posedge <= 0;
    end
    else begin
        if ((cnt == 500)) begin
            cnt <= 1;
            clk_io <= (!clk_io);
            if ((!clk_io)) begin
                clk_io_posedge <= 1'b1;
            end
        end
        else begin
            cnt <= (cnt + 1);
            clk_io_posedge <= 1'b0;
        end
    end
end

endmodule
